spring:
  application:
    name: Document-Service
  config:
    activate:
      on-profile: prod
  cache:
    type: redis
    cache-names: redis-cache
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/stroy1click
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost:5432/stroy1click
    user: postgres
    password: password
    baseline-on-migrate: true
  messages:
    basename: messages
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  threads:
    virtual:
      enabled: true

otel:
  service:
    name: "document-service"
  traces:
    exporter: "otlp"
    sampler: "always_on"
  metrics:
    exporter: "otlp"
    export:
      interval: 5000
  logs:
    exporter: "otlp"
  exporter:
    otlp:
      protocol: "grpc"
      endpoint: "http://localhost:4317"

server:
  port: 6065

redisson:
  host: 127.0.0.1
  port: 6379
  username: default
  password: password

s3:
  access-key: b0a085fad6914c2abd49b762ee2263e2
  secret-key: 2bd487564bb54e9a8231bb3944108971
  region: ru-7
  bucket-name: stroy1click
  storage-url: https://s3.twcstorage.ru
