create schema if not exists documents;

create table if not exists documents.document(
    id bigint primary key generated by default as identity ,
    link varchar not null ,
    type varchar not null ,
    user_id bigint not null
);

create schema if not exists outbox;

create table if not exists outbox.processed_events(
    id bigint generated by default as identity primary key ,
    message_id bigint not null
);

--- 1 - get
--- 2 - update
--- 3 - delete Не ставить в REFERENCES

-- ---------- DOCUMENT ----------

-- Test: DocumentControllerIT getByLink()
-- Описание: получение документа по id
insert into documents.document(id, link, type, user_id) values (1, 'get-document-link.pdf', 'SALES_AGREEMENT', 500);

-- Test: DocumentControllerIT delete()
-- Описание: удаление документа по id
insert into documents.document(id, link, type, user_id) values (3, 'delete-document-link.pdf', 'SALES_AGREEMENT', 500);

-- Test: DocumentControllerIT getByUserId()
-- Описание: получение всех документов по userId
insert into documents.document(id, link, type, user_id) values (4, 'get-by-userId-document-link.pdf', 'SALES_AGREEMENT', 400);
insert into documents.document(id, link, type, user_id) values (5, 'get-by-userId-document-link.pdf', 'SALES_AGREEMENT', 400);
insert into documents.document(id, link, type, user_id) values (6, 'get-by-userId-document-link.pdf', 'SALES_AGREEMENT', 400);