create schema if not exists documents;

create table if not exists documents.document(
    id bigint primary key generated by default as identity ,
    link varchar not null ,
    type varchar not null ,
    user_id bigint not null
);
